from .banana import check_banana
from .data_processor import DataProcessor
from .glass import check_glass
from .haberman import check_haberman
from .iris import check_iris
from .magic import check_magic
from .mammographic import check_mammographic
from .newthyroid import check_newthyroid
from .segment import check_segment
from .titanic import check_titanic
from .wine import check_wine
